api_key = "f0fc4c668392f9f9a447e48584c214ee"
provinces = [0, 340000, 110000, 500000, 350000, 620000, 440000, 450000, 520000, 460000, 130000, 410000, 230000, 420000, 430000, 220000, 320000, 360000, 210000, 150000, 640000, 630000, 370000, 140000, 610000, 310000, 510000, 540000, 650000, 660000, 530000, 330000]
